-- CREATE TABLE PERSONSS(ID INTEGER NOT NULL PRIMARY KEY, NAME NOT NULL, 
-- ADDRESS NOT NULL, PHONENUM INTEGER NOT NULL); 

-- INSERT INTO PERSONSS(ID, NAME, ADDRESS, PHONENUM)
-- VALUES(123313, 'BRYAN', 'LAWAAN', 09958855240)

-- SELECT * FROM PERSONSS;

-- UPDATE PERSONSS
-- SET PHONENUM = 9480020851
-- WHERE ID = 123313;

-- CREATE TABLE SAMPLE (sampid INTEGER NOT NULL PRIMARY KEY, 
-- sampName TEXT NOT NULL,
-- sampEmail TEXT NOT NULL);

INSERT INTO SAMPLE(sampid, sampName, sampEmail)
VALUES(123, 'BRY', 'BRY@GMAIL.COM')


SELECT * FROM SAMPLE
